# Generated by Django 2.2 on 2021-12-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='item_image',
            field=models.ImageField(default='recipepic.jpg', upload_to='recipe_pictures'),
        ),
    ]
