# Generated by Django 2.2 on 2021-12-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_user', models.CharField(max_length=500)),
                ('item_recipeid', models.CharField(max_length=500)),
            ],
        ),
    ]
