# Generated by Django 2.2 on 2021-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_savedrecipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='item_category',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
