# Generated by Django 2.2 on 2021-12-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='item_category',
            field=models.CharField(choices=[('chinese', 'CHINESE'), ('indian', 'INDIAN'), ('mexican', 'MEXICAN'), ('american', 'AMERICAN')], default='None', max_length=500),
        ),
    ]
