# Generated by Django 2.2 on 2021-12-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211215_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='item_category',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Mexican', 'Mexican'), ('American', 'American')], default='None', max_length=500),
        ),
    ]
